service: serverless-bolt-js
frameworkVersion: "2"
useDotenv: true
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-3
  lambdaHashingVersion: 20201221
  environment:
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
    SLACK_BOT_TOKEN: ${env:SLACK_BOT_TOKEN}
functions:
  slack:
    handler: app.handler
    events:
      - http:
          path: slack/events
          method: post
  sendmessage:
    handler: notify.sendMessage
    events:
      - schedule:
          rate:
            - cron(0 11 ? * 1-5 *)
plugins:
  - serverless-offline
